#!/usr/bin/env bash
# Loop from 1 to 100
for i in $(seq 1 100); do
    # Check if number is divisible by both 3 and 5
    if [ $((i % 3)) -eq 0 ] && [ $((i % 5)) -eq 0 ]; then
        echo "FizzBuzz"
    # Check if number is divisible by 3
    elif [ $((i % 3)) -eq 0 ]; then
        echo "Fizz"
    # Check if number is divisible by 5
    elif [ $((i % 5)) -eq 0 ]; then
        echo "Buzz"
    # Otherwise, print the number
    else
        echo "$i"
    fi
done
